// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1RGu372wczANxJq0VQvdMUaqFq6rCZM',
    appId: '1:1057394469858:web:d3601579b44ecb1ac567bb',
    messagingSenderId: '1057394469858',
    projectId: 'sign-in-providers-test',
    authDomain: 'sign-in-providers-test.firebaseapp.com',
    storageBucket: 'sign-in-providers-test.appspot.com',
    measurementId: 'G-PV8MNZM8KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfhXoW-SSKOuctk98K1qhxNcldc3WraqU',
    appId: '1:1057394469858:android:806db2533a72e0dcc567bb',
    messagingSenderId: '1057394469858',
    projectId: 'sign-in-providers-test',
    storageBucket: 'sign-in-providers-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY0ZobdBxT7QTtYspucm9XVuptZ4fR5wU',
    appId: '1:1057394469858:ios:47f96d873af2ad58c567bb',
    messagingSenderId: '1057394469858',
    projectId: 'sign-in-providers-test',
    storageBucket: 'sign-in-providers-test.appspot.com',
    iosClientId: '1057394469858-brm1g9jve8631m9aeea4cao3bpnd9gkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.signInWithGoogleFacebookAndAppleTest',
  );
}
